import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Script from 'next/script';
import Head from 'next/head';
import { esriConfig } from '@/config/esri';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <Head>
        <Script>   
            {esriConfig}
        </Script>
        {/* <Script
          type='module'
          src='https://js.arcgis.com/calcite-components/3.0.3/calcite.esm.js'
        ></Script>

        <link
          rel='stylesheet'
          href='https://js.arcgis.com/4.32/esri/themes/light/main.css'
        />
        <Script src='https://js.arcgis.com/4.32/'></Script>
        <Script
          type='module'
          src='https://js.arcgis.com/map-components/4.32/arcgis-map-components.esm.js'
        ></Script> */}
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
